const { test, expect } = require('@playwright/test');
async function openApp(page){await page.addInitScript(()=>{window.__GAMA_E2E__=true});await page.goto('/index.html',{waitUntil:'domcontentloaded'});await expect(page.locator('body')).toBeVisible()}
async function auth(page){await page.evaluate(()=>{localStorage.setItem('gama_session_v1',JSON.stringify({userId:'e2e-user',role:'admin',username:'e2e@gama.local',name:'E2E Administrator'}));window.GamaAccessControl?.sync();window.dispatchEvent(new CustomEvent('gama:auth-ready'))});await expect(page.locator('#gamaAccessUser')).toBeVisible({timeout:10000});await expect(page.locator('#mainmenu .gamaF2Grid')).toBeVisible({timeout:10000})}
async function openModule(page,id){const card=page.locator(`#mainmenu [data-gama-module="${id}"]`);await expect(card).toHaveCount(1,{timeout:10000});await expect(card).toBeEnabled();await card.click()}
async function menu(page){await page.evaluate(()=>window.showTab('mainmenu',null));await expect(page.locator('#mainmenu')).toBeVisible();await expect(page.locator('#mainmenu')).not.toHaveAttribute('hidden')}
test('GAMA loads without uncaught page errors',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await openApp(page);expect(errors).toEqual([])});
test('admin menu has the GAMA visual shortcuts and no delivery tile',async({page})=>{await page.setViewportSize({width:390,height:844});await openApp(page);await auth(page);const cards=page.locator('#mainmenu .gamaF2Card');await expect(cards).toHaveCount(17);for(const id of ['gamaPurchasesV14','dashboard','products','clients','customer-requests','excel-import','movement','billing','stock','audit','suppliers','reports','settings','backup','users','barcode','client-catalog'])await expect(page.locator(`#mainmenu [data-gama-module="${id}"]`)).toHaveCount(1);await expect(page.locator('#mainmenu .gamaF2Card').filter({hasText:/TMS|Entregas|Livraisons/i})).toHaveCount(0);const excel=page.locator('#mainmenu [data-gama-module="excel-import"]');await expect(excel).toBeEnabled();await expect(excel.locator('svg')).toBeVisible();await expect(excel.boundingBox()).resolves.toBeTruthy()});
test('cloud accounts can create a client account',async({page})=>{await openApp(page);await auth(page);await page.locator('#gamaCloudAdminBtn').click();await expect(page.locator('#gamaCloudAdmin')).toContainText('Crear una cuenta');await expect(page.locator('#gamaCloudAdmin [name="role"] option[value="cliente"]')).toHaveCount(1);await page.evaluate(()=>{window.GamaCloud.getSession=async()=>({data:{session:{access_token:'e2e-token'}}});window.GamaCloud.list=async()=>({data:[],error:null})});let body=null;await page.route('**/functions/v1/gama-admin-users',async route=>{body=JSON.parse(route.request().postData()||'{}');await route.fulfill({status:201,contentType:'application/json',body:JSON.stringify({id:'e2e-client',email:body.email,full_name:body.full_name,role:body.role})})});await page.locator('#gamaCloudAdmin [name="full_name"]').fill('Cliente E2E');await page.locator('#gamaCloudAdmin [name="email"]').fill('cliente-e2e@example.com');await page.locator('#gamaCloudAdmin [name="password"]').fill('E2Esecure123!');await page.locator('#gamaCloudAdmin [name="role"]').selectOption('cliente');await page.locator('#gamaCreateSubmit').click();await expect(page.locator('[data-create-status]')).toContainText('Cuenta creada correctamente');expect(body).toEqual({full_name:'Cliente E2E',email:'cliente-e2e@example.com',password:'E2Esecure123!',role:'cliente'})});
test('Excel module opens with the three import types',async({page})=>{await openApp(page);await auth(page);await openModule(page,'excel-import');const excel=page.locator('#excelImport');await expect(excel).toBeVisible();await expect(excel).not.toHaveAttribute('hidden');await expect(excel.locator('[data-gxi-type="products"]')).toBeVisible();await expect(excel.locator('[data-gxi-type="clients"]')).toBeVisible();await expect(excel.locator('[data-gxi-type="suppliers"]')).toBeVisible();await expect(excel.locator('#gxiFile')).toBeVisible();await expect(excel.locator('#gxiImport')).toBeDisabled();await excel.locator('[data-gxi-type="clients"]').click();await expect(excel.locator('[data-gxi-type="clients"]')).toHaveClass(/active/);await excel.locator('[data-gxi-type="suppliers"]').click();await expect(excel.locator('[data-gxi-type="suppliers"]')).toHaveClass(/active/);await excel.locator('[data-gxi-type="products"]').click();await expect(excel.locator('[data-gxi-type="products"]')).toHaveClass(/active/);await menu(page)});
test('core customer modules remain navigable',async({page})=>{await openApp(page);await auth(page);for(const [id,section] of [['dashboard','#dashboard'],['products','#products'],['client-catalog','#client-catalog'],['customer-requests','#customer-requests']]){await openModule(page,id);await expect(page.locator(section)).toBeVisible();await menu(page)}});
test('logout clears the GAMA session',async({page})=>{await openApp(page);await auth(page);await page.locator('#gamaAccessLogout').click({force:true});await expect(page.locator('#gamaAccessUser')).toHaveCount(0,{timeout:15000});expect(await page.evaluate(()=>localStorage.getItem('gama_session_v1'))).toBeNull()});
