import fs from 'node:fs';

const indexPath = 'index.html';
const cssPath = 'gama-core.css';

let html = fs.readFileSync(indexPath, 'utf8');
const original = html;

// 1. Remove the legacy inline business core now provided by gama-legacy-core.js.
const legacyCorePattern = /\n?\s*<script\b[^>]*>\s*const\s+KEY\s*=\s*['"]stock_manager_v6_ecuador['"][\s\S]*?renderAll\(\);\s*showTab\(['"]mainmenu['"],\s*null\);\s*<\/script>\s*/i;
html = html.replace(legacyCorePattern, '\n');

// 2. Remove the repeated legacy barcode MutationObserver compatibility blocks.
const barcodeObserverPattern = /\n?\s*<script\b[^>]*>\s*\(function\(\)\{[\s\S]*?new\s+MutationObserver\(cleanup\)\.observe\(document\.body,\{subtree:true,childList:true\}\);[\s\S]*?\}\)\(\);\s*<\/script>\s*/gi;
html = html.replace(barcodeObserverPattern, '\n');

// 3. Move all inline CSS into one external stylesheet, preserving cascade order.
const styles = [];
html = html.replace(/<style\b[^>]*>([\s\S]*?)<\/style>/gi, (_match, css, offset) => {
  styles.push(`/* Original inline style block ${styles.length + 1} */\n${css.trim()}\n`);
  return `\n<!-- CSS extracted by GAMA index refactor -->\n`;
});

if (styles.length) {
  const css = `/* GAMA Stock Manager V10 - extracted stylesheet.\n * Generated by scripts/refactor-index.mjs.\n * Cascade order intentionally preserves the legacy index.html order.\n */\n\n${styles.join('\n')}`;
  fs.writeFileSync(cssPath, css, 'utf8');
}

// 4. Add the stylesheet link once, immediately after the manifest link.
if (!/<link\s+rel=["']stylesheet["']\s+href=["']gama-core\.css/i.test(html)) {
  const marker = '<link rel="manifest" href="manifest.json">';
  if (!html.includes(marker)) throw new Error('Expected manifest link not found in index.html');
  html = html.replace(marker, `${marker}\n<link rel="stylesheet" href="gama-core.css?v=1">`);
}

// 5. Ensure the extracted legacy core is explicitly loaded before standard UI.
if (!/gama-legacy-core\.js\?v=1/.test(html)) {
  const standardUi = '<script src="gama-standard-ui.js?v=8"></script>';
  if (!html.includes(standardUi)) throw new Error('Expected gama-standard-ui.js script tag not found');
  html = html.replace(standardUi, '<script src="gama-legacy-core.js?v=1"></script>\n' + standardUi);
}

// Remove excessive blank lines introduced by block removal.
html = html.replace(/\n{4,}/g, '\n\n\n');

if (html === original) {
  console.log('index.html already clean; no changes required.');
  process.exit(0);
}

fs.writeFileSync(indexPath, html, 'utf8');
console.log(`Refactored ${indexPath}; extracted ${styles.length} CSS block(s).`);
